version: "3"

services:
  spark-dependency:
    environment:
      - STORAGE=elasticsearch
      - ES_NODES=https://127.0.0.1:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=123456
      - ES_NODES_WAN_ONLY=true
    image: spark-dependency
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 6G