version: "3"

services:
  spark-dependency:
    environment:
      - STORAGE=elasticsearch
      - ES_NODES=https://10.6.1.111:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=123456
      - ES_NODES_WAN_ONLY=true
    image: spark-dependency
    volumes:
      - /elk-docker/elk/elasticsearch1/config/certs:/usr/local/share/certs/
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 6G